# Generated by Django 4.0.4 on 2022-04-19 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_text_post_author_post_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('target_amount', models.IntegerField()),
                ('one_amount', models.IntegerField()),
                ('d_day', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('funding_rate', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('n', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
