# Generated by Django 4.0.4 on 2022-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_goods_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='funding_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
